{% set name = "laspy" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 139ac04c7f2983d790eeb07305497477bf1fb430f7a0eab61cee1c6eb0656b10

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - laspy
  requires:
    - pytest
  source_files:
    - tests/*
  commands:
    - pytest -v

about:
  home: https://github.com/laspy/laspy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Native Python ASPRS LAS read/write library

  description: |
    Laspy is a python library for reading, modifying and creating LAS LiDAR files.
  doc_url: https://laspy.readthedocs.io/en/latest/
  dev_url: https://github.com/laspy/laspy

extra:
  recipe-maintainers:
    - plimkilde
    - hobu
    - chambbj
