travis:
  secure:
    BINSTAR_TOKEN: lEYyxiJnlvK0uBiqCjmDmVYfXdTiQShX4ocihQHvqrIXTIBu4fRSeMQk4pHmdsgD32qiXE9q+3QW4e3wOTKvCzLI/2AjwfMI2/BEdDrokGKZA879qKViF+2RIKX5AFi6ek+yySoH33fVWYg7DGhW0SpcbG38O1aR1NCoHkXftwgZSkiRbEuX4/jrxuUDNNNYnwj5tA19UjUMA+ZwbZu66jqCbBjoTmEQ8hIr9N2fhQyrqQvz1aGSHOHt4igBHhJx/Q2dpAPbbp2/ibf0WprRXq1kGwR8bGyWvRrcZC00JmptKYg0ClTuyDlDcQ1HNxUSLmhvPF0tDOjw7Xt+Bb+2dI/3Ds4viGSJbmALhrqIqnbfU9DL+HzKJaqmlw93x7dkMysmUvpkXjmdBeSElO6fqddobzcgp8VM8C6Z1ybmPvM61wy6H/xU9b5me2KBlFLGwDHatWOt+WIyDoVe0/6kFvB63aM4AystG1QBdq9856OozZDWGNHX2K9xPEOB2fCOywwlQMCCQZfDjYr2ihxM85fx8NNlMe0DEYQq5UKjsNqIKA4Nt5eQfwKnMgXb/DdZBxL2YEWr7fANdva2VHzuy0twt1iIhiJX0/ylvYJVQu2JNsaQZg5YGa04tZPC088Fou/v+DMg0XNWxs9kRJeZkxeSIaqNYPC23u0poVLfQDo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
